name: Build

on: [push]

jobs:

  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21.0'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: building project
      run: make build